# Generated by Django 3.0.3 on 2020-02-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponseA', models.TextField()),
                ('reponseB', models.TextField()),
                ('reponseC', models.TextField()),
                ('reponseD', models.TextField()),
                ('bonneReponse', models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])),
                ('pireReponse', models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_choisie', models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])),
                ('score', models.IntegerField(blank=True, null=True)),
                ('question_coresponddante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDuQuizz', models.TextField(blank=True, null=True)),
                ('questions', models.ManyToManyField(to='polls.Question')),
            ],
        ),
    ]
