# Generated by Django 3.0.3 on 2020-03-09 16:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizz_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('date', models.TimeField(default=datetime.datetime(2020, 3, 9, 16, 15, 37, 108722, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Question_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponseA', models.TextField()),
                ('reponseB', models.TextField()),
                ('reponseC', models.TextField()),
                ('reponseD', models.TextField()),
                ('caracteristic_value_1', models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])),
                ('caracteristic_value_2', models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])),
                ('caracteristic_value_3', models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])),
                ('caracteristic_value_4', models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])),
            ],
        ),
        migrations.CreateModel(
            name='Reponse_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_choisie', models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])),
                ('score_value_1', models.IntegerField(blank=True, null=True)),
                ('score_value_2', models.IntegerField(blank=True, null=True)),
                ('score_value_3', models.IntegerField(blank=True, null=True)),
                ('score_value_4', models.IntegerField(blank=True, null=True)),
                ('question_coresponddante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question_value')),
            ],
        ),
        migrations.CreateModel(
            name='Quizz_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDuQuizz', models.TextField(blank=True, null=True)),
                ('caracteristic_value_1_name', models.TextField()),
                ('caracteristic_value_2_name', models.TextField()),
                ('caracteristic_value_3_name', models.TextField()),
                ('caracteristic_value_4_name', models.TextField()),
                ('questions', models.ManyToManyField(to='polls.Question_value')),
            ],
        ),
    ]
