# Generated by Django 3.0.3 on 2020-03-09 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_historic_question_value_quizz_value_reponse_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='historic',
            name='quizz_value_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Quizz_value'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='date',
            field=models.TimeField(default=datetime.datetime(2020, 3, 9, 16, 35, 13, 590752, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historic',
            name='quizz_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Quizz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='question',
            name='reponseA',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='question',
            name='reponseB',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='question',
            name='reponseC',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='question',
            name='reponseD',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='question_value',
            name='question',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='question_value',
            name='reponseA',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='question_value',
            name='reponseB',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='question_value',
            name='reponseC',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='question_value',
            name='reponseD',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='nomDuQuizz',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='quizz_value',
            name='caracteristic_value_1_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='quizz_value',
            name='caracteristic_value_2_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='quizz_value',
            name='caracteristic_value_3_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='quizz_value',
            name='caracteristic_value_4_name',
            field=models.CharField(max_length=400),
        ),
    ]
